name: Pull Request
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: 'requirements*.txt'
      - name: Install
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: PR Lint
        run: echo "${{ github.event.pull_request.title }}" | python -m commitizen check
      - name: Commitlint
        run: cz check --rev-range origin/main..HEAD
      - name: Lint
        run: python -m flake8 custom_components/
      - name: Test
        run: python -m pytest test/
