name: Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: 'requirements*.txt'
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Install
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Lint
        run: flake8 custom_components/
      - name: Test
        run: pytest test/

      - name: Versioning and Tags
        run: |
          cz bump --changelog --yes
          git push origin main
          git push origin --tags
          echo "RELEASE_TAG=$(cz version --project)" >> $GITHUB_ENV
      - name: GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $RELEASE_TAG --notes-file CHANGELOG.md --verify-tag
